
uanxasigxivehhtokacb = "project_id"

[global.env]
OPTA_FIFA_API_KEY = "env:OPTA_FIFA_API_KEY"
OPTA_FIFA_API_BASE_URL = "env:OPTA_FIFA_API_BASE_URL"
TRANSFER_MARKET_API_KEY = "env:TRANSFER_MARKET_API_KEY"
TRANSFER_MARKET_API_BASE_URL = "env:TRANSFER_MARKET_API_BASE_URL"
SUPABASE_URL = "env:SUPABASE_URL"
SUPABASE_SERVICE_ROLE_KEY = "env:SUPABASE_SERVICE_ROLE_KEY"
