
import { KagglePlayerData, KaggleTeamData, SportsVideoAnalysisData } from './types';

// Mock Kaggle player database
export const kagglePlayerDatabase: KagglePlayerData[] = [
  {
    player_id: "k001",
    name: "محمد صلاح",
    team: "ليفربول",
    position: "RW",
    nationality: "مصر",
    age: 31,
    height_cm: 175,
    weight_kg: 73,
    overall_rating: 89,
    potential: 89,
    value_eur: 65000000,
    wage_eur: 350000,
    preferred_foot: "اليسار",
    weak_foot: 3,
    skill_moves: 4,
    international_reputation: 4,
    pace: 90,
    shooting: 87,
    passing: 82,
    dribbling: 90,
    defending: 45,
    physic: 75
  },
  {
    player_id: "k002",
    name: "كريم بنزيما",
    team: "الاتحاد",
    position: "ST",
    nationality: "فرنسا",
    age: 35,
    height_cm: 185,
    weight_kg: 81,
    overall_rating: 88,
    potential: 88,
    value_eur: 35000000,
    wage_eur: 450000,
    preferred_foot: "اليمين",
    weak_foot: 4,
    skill_moves: 4,
    international_reputation: 5,
    pace: 80,
    shooting: 88,
    passing: 83,
    dribbling: 87,
    defending: 39,
    physic: 78
  },
  {
    player_id: "k003",
    name: "رونالدو",
    team: "النصر",
    position: "ST",
    nationality: "البرتغال",
    age: 38,
    height_cm: 187,
    weight_kg: 85,
    overall_rating: 86,
    potential: 86,
    value_eur: 20000000,
    wage_eur: 400000,
    preferred_foot: "اليمين",
    weak_foot: 4,
    skill_moves: 5,
    international_reputation: 5,
    pace: 85,
    shooting: 92,
    passing: 79,
    dribbling: 85,
    defending: 34,
    physic: 75
  },
  {
    player_id: "k004",
    name: "نيمار",
    team: "الهلال",
    position: "LW",
    nationality: "البرازيل",
    age: 31,
    height_cm: 175,
    weight_kg: 68,
    overall_rating: 87,
    potential: 87,
    value_eur: 40000000,
    wage_eur: 380000,
    preferred_foot: "اليمين",
    weak_foot: 5,
    skill_moves: 5,
    international_reputation: 5,
    pace: 87,
    shooting: 83,
    passing: 85,
    dribbling: 93,
    defending: 30,
    physic: 61
  },
  {
    player_id: "k005",
    name: "سالم الدوسري",
    team: "الهلال",
    position: "RW",
    nationality: "المملكة العربية السعودية",
    age: 31,
    height_cm: 168,
    weight_kg: 65,
    overall_rating: 82,
    potential: 82,
    value_eur: 15000000,
    wage_eur: 120000,
    preferred_foot: "اليمين",
    weak_foot: 3,
    skill_moves: 4,
    international_reputation: 2,
    pace: 88,
    shooting: 82,
    passing: 80,
    dribbling: 85,
    defending: 40,
    physic: 70
  },
  {
    player_id: "k006",
    name: "سعود عبدالحميد",
    team: "النصر",
    position: "GK",
    nationality: "المملكة العربية السعودية",
    age: 29,
    height_cm: 190,
    weight_kg: 85,
    overall_rating: 80,
    potential: 81,
    value_eur: 10000000,
    wage_eur: 80000,
    preferred_foot: "اليمين",
    weak_foot: 2,
    skill_moves: 1,
    international_reputation: 1,
    pace: 50,
    shooting: 20,
    passing: 60,
    dribbling: 30,
    defending: 25,
    physic: 75
  }
];

// Mock Kaggle team database
export const kaggleTeamDatabase: KaggleTeamData[] = [
  {
    team_id: "kt001",
    name: "الهلال",
    league: "دوري روشن السعودي",
    country: "المملكة العربية السعودية",
    attack: 85,
    midfield: 83,
    defense: 82,
    overall: 84,
    team_logo: "alhilal.png"
  },
  {
    team_id: "kt002",
    name: "النصر",
    league: "دوري روشن السعودي",
    country: "المملكة العربية السعودية",
    attack: 84,
    midfield: 82,
    defense: 80,
    overall: 82,
    team_logo: "alnasser.png"
  },
  {
    team_id: "kt003",
    name: "الاتحاد",
    league: "دوري روشن السعودي",
    country: "المملكة العربية السعودية",
    attack: 83,
    midfield: 81,
    defense: 80,
    overall: 81,
    team_logo: "alittihad.png"
  },
  {
    team_id: "kt004",
    name: "ليفربول",
    league: "الدوري الإنجليزي الممتاز",
    country: "إنجلترا",
    attack: 88,
    midfield: 85,
    defense: 86,
    overall: 86,
    team_logo: "liverpool.png"
  }
];

// Mock sports video analysis database
export const sportsVideoAnalysisDatabase: SportsVideoAnalysisData[] = [
  {
    analysis_id: "sva001",
    match_id: "m2023_01",
    player_id: "k001",
    player_name: "محمد صلاح",
    team_name: "ليفربول",
    event_type: "تمريرة",
    timestamp: 1235,
    field_position_x: 75.5,
    field_position_y: 32.1,
    movement_speed: 21.3,
    success_rate: 0.92,
    confidence_score: 0.95
  },
  {
    analysis_id: "sva002",
    match_id: "m2023_01",
    player_id: "k002",
    player_name: "كريم بنزيما",
    team_name: "الاتحاد",
    event_type: "تسديدة",
    timestamp: 2145,
    field_position_x: 85.3,
    field_position_y: 50.2,
    movement_speed: 18.7,
    success_rate: 0.78,
    confidence_score: 0.89
  },
  {
    analysis_id: "sva003",
    match_id: "m2023_02",
    player_id: "k003",
    player_name: "رونالدو",
    team_name: "النصر",
    event_type: "عرضية",
    timestamp: 1892,
    field_position_x: 82.6,
    field_position_y: 12.4,
    movement_speed: 22.5,
    success_rate: 0.85,
    confidence_score: 0.91
  },
  {
    analysis_id: "sva004",
    match_id: "m2023_02",
    player_id: "k004",
    player_name: "نيمار",
    team_name: "الهلال",
    event_type: "مراوغة",
    timestamp: 2356,
    field_position_x: 65.8,
    field_position_y: 22.7,
    movement_speed: 24.1,
    success_rate: 0.95,
    confidence_score: 0.97
  },
  {
    analysis_id: "sva005",
    match_id: "m2023_03",
    player_id: "k005",
    player_name: "سالم الدوسري",
    team_name: "الهلال",
    event_type: "استحواذ",
    timestamp: 1457,
    field_position_x: 45.2,
    field_position_y: 38.9,
    movement_speed: 19.6,
    success_rate: 0.88,
    confidence_score: 0.93
  },
  {
    analysis_id: "sva006",
    match_id: "m2023_03",
    player_id: "k006",
    player_name: "سعود عبدالحميد",
    team_name: "النصر",
    event_type: "تصدي",
    timestamp: 2567,
    field_position_x: 12.3,
    field_position_y: 50.1,
    movement_speed: 15.2,
    success_rate: 0.91,
    confidence_score: 0.94
  }
];
