// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uanxasigxivehhtokacb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhbnhhc2lneGl2ZWhodG9rYWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDMxODAsImV4cCI6MjA1NzYxOTE4MH0.zIZt8d9YIxokMwt2fDmnLZpvymhV4B78G0mChdO2gjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);